# Generated by Django 4.2.13 on 2024-07-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='national_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
