# Generated by Django 4.2.13 on 2024-07-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0003_tenant_landlord'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('landlord', 'Landlord'), ('tenant', 'Tenant'), ('admin', 'Admin')], default='tenant', max_length=10),
        ),
        migrations.AddField(
            model_name='landlord',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
