# Generated by Django 4.2.13 on 2024-07-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0005_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='landlord',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
