# Generated by Django 4.2.13 on 2024-07-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0006_landlord_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('change_customuser_model', 'Can change custom user'), ('delete_customuser_model', 'Can delete custom user')]},
        ),
    ]
