# Generated by Django 4.2.13 on 2024-07-17 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0007_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('customusers_add_building', 'Can add building'), ('customusers_change_building', 'Can change building'), ('customusers_delete_building', 'Can delete building')]},
        ),
    ]
