# Generated by Django 4.2.13 on 2024-07-17 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0008_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landlord',
            options={'permissions': [('landlord_add_building', 'Can add building')]},
        ),
    ]
