# Generated by Django 4.2.13 on 2024-07-17 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0009_alter_landlord_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='landlord',
            options={},
        ),
    ]
