# Generated by Django 4.2.13 on 2024-07-17 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0010_alter_landlord_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.RemoveField(
            model_name='landlord',
            name='is_admin',
        ),
    ]
