# Generated by Django 4.2.13 on 2024-07-01 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketing',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='marketing_campaigns', to='products.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=1, upload_to='products/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
