# Generated by Django 4.2.13 on 2024-07-03 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_featurevalue'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFeatureValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productfeature')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_values', to='products.product')),
            ],
        ),
    ]
