# Generated by Django 4.2.13 on 2024-07-02 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_marketing_products_product_image'),
        ('orders', '0004_order_is_paid_order_total_price_orderitem_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'product')},
        ),
    ]
