# Generated by Django 4.2.13 on 2024-07-07 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/properties'),
        ),
    ]
