# Generated by Django 4.2.13 on 2024-07-04 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_remove_property_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='price_per_night',
            new_name='price',
        ),
    ]
