# Generated by Django 4.2.13 on 2024-07-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_propertyimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimages',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/properties/'),
        ),
    ]
