# Generated by Django 4.2.13 on 2024-07-04 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_rename_price_per_night_property_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='for_rent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='property',
            name='for_sale',
            field=models.BooleanField(default=True),
        ),
    ]
