# Generated by Django 4.2.13 on 2024-07-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_alter_propertyimages_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='sale_type',
        ),
        migrations.AddField(
            model_name='property',
            name='is_rented',
            field=models.BooleanField(default=False),
        ),
    ]
