# Generated by Django 4.2.13 on 2024-07-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_for_rent_property_for_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='for_rent',
        ),
        migrations.RemoveField(
            model_name='property',
            name='for_sale',
        ),
        migrations.AddField(
            model_name='property',
            name='sale_type',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale')], default=2, max_length=10),
            preserve_default=False,
        ),
    ]
