# Generated by Django 4.2.13 on 2024-07-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_remove_property_for_rent_remove_property_for_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='properties_images/'),
        ),
    ]
