# Generated by Django 4.2.13 on 2024-07-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_remove_property_end_date_remove_property_start_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='square_meters',
        ),
        migrations.AddField(
            model_name='propertydetails',
            name='square_meters',
            field=models.DecimalField(decimal_places=2, default=11, max_digits=6),
            preserve_default=False,
        ),
    ]
