# Generated by Django 4.2.13 on 2024-07-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_remove_property_square_meters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydetails',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/properties/'),
        ),
    ]
