# Generated by Django 4.2.13 on 2024-07-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_propertydetails_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='square_meters',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
