# Generated by Django 4.2.13 on 2024-07-08 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_alter_propertydetails_square_meters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyImages',
        ),
    ]
