# Generated by Django 4.2.13 on 2024-07-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_propertyimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyImages',
        ),
    ]
