# Generated by Django 4.2.13 on 2024-07-08 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0013_delete_propertyimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertydetails',
            name='images',
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/properties/')),
                ('property_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.propertydetails')),
            ],
        ),
    ]
