# Generated by Django 4.2.13 on 2024-07-08 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0003_tenant_landlord'),
        ('properties', '0014_remove_propertydetails_images_propertyimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='customusers.tenant'),
        ),
    ]
