# Generated by Django 4.2.13 on 2024-07-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_property_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertydetails',
            name='number_floors',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propertydetails',
            name='square_meters',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
