# Generated by Django 4.2.13 on 2024-07-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0016_alter_propertydetails_number_floors_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
    ]
