# Generated by Django 4.2.13 on 2024-07-10 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0018_building_remove_property_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='location',
        ),
        migrations.AlterField(
            model_name='building',
            name='building_type',
            field=models.CharField(choices=[('house', 'House'), ('apartment', 'Apartment'), ('villa', 'Villa'), ('studio', 'Studio'), ('office', 'Office'), ('other', 'Other'), ('residential', 'Residential'), ('office', 'Office')], max_length=50),
        ),
    ]
