# Generated by Django 4.2.13 on 2024-07-10 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0019_remove_building_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='is_rented',
        ),
    ]
