# Generated by Django 4.2.13 on 2024-07-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0020_remove_property_is_rented'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={},
        ),
        migrations.AddField(
            model_name='building',
            name='rental_apartment_count',
            field=models.IntegerField(default=0),
        ),
    ]
