# Generated by Django 4.2.13 on 2024-07-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0021_alter_property_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertydetails',
            name='property',
        ),
        migrations.RemoveField(
            model_name='propertyimage',
            name='property_details',
        ),
        migrations.RemoveField(
            model_name='building',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='building',
            name='number_floors',
        ),
        migrations.AddField(
            model_name='building',
            name='floors',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47'), (48, '48'), (49, '49'), (50, '50')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='building_age',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47'), (48, '48'), (49, '49'), (50, '50')]),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_type',
            field=models.CharField(choices=[('apart', 'Apart'), ('apartment', 'Apartman'), ('office', 'Ofis'), ('house', 'Ev'), ('villa', 'Villa'), ('other', 'Diğer')], max_length=50),
        ),
        migrations.AlterField(
            model_name='building',
            name='rental_apartment_count',
            field=models.PositiveIntegerField(),
        ),
        migrations.DeleteModel(
            name='Property',
        ),
        migrations.DeleteModel(
            name='PropertyDetails',
        ),
        migrations.DeleteModel(
            name='PropertyImage',
        ),
    ]
