# Generated by Django 4.2.13 on 2024-07-11 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0022_remove_propertydetails_property_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='building_type',
            field=models.CharField(choices=[('apart', 'Apart'), ('apartment', 'Apartman'), ('office', 'Ofis'), ('house', 'Ev'), ('villa', 'Villa'), ('other', 'Diğer')], max_length=10),
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('floor', models.PositiveIntegerField()),
                ('rooms', models.PositiveIntegerField()),
                ('area', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_rented', models.BooleanField(default=False)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='properties.building')),
            ],
        ),
    ]
