# Generated by Django 4.2.13 on 2024-07-11 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0023_alter_building_building_type_apartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='balcony',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='elevator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='furnished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apartment',
            name='image',
            field=models.ImageField(default=1, upload_to='images/properties/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apartment',
            name='parking',
            field=models.BooleanField(default=False),
        ),
    ]
