# Generated by Django 4.2.13 on 2024-07-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0024_apartment_balcony_apartment_elevator_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='floors',
        ),
        migrations.AddField(
            model_name='apartment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='building',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='image',
            field=models.ImageField(upload_to='images/apartment/'),
        ),
        migrations.AlterField(
            model_name='building',
            name='building_age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='building',
            name='rental_apartment_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
