# Generated by Django 4.2.13 on 2024-07-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0025_remove_building_floors_apartment_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='floors',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
