# Generated by Django 4.2.13 on 2024-07-14 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0003_tenant_landlord'),
        ('properties', '0026_building_floors'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='landlord',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='customusers.landlord'),
            preserve_default=False,
        ),
    ]
