# Generated by Django 4.2.13 on 2024-07-17 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0028_alter_building_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={},
        ),
    ]
