# Generated by Django 4.2.13 on 2024-07-14 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customusers', '0003_tenant_landlord'),
        ('properties', '0027_building_landlord'),
        ('contract', '0002_alter_contract_landlord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='landlord',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='contract',
            name='apartment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.apartment'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customusers.tenant'),
        ),
    ]
