# Generated by Django 4.2.13 on 2024-07-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0003_remove_contract_landlord_remove_contract_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
